@Base_url=http://localhost:8801/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNkYTA1ZWVjLTI1ZWEtNGQ0NC05ZmQ1LTQ1ODkxYzc2ZGI5MSIsImlhdCI6MTc4NzI0NzM3MSwiZXhwIjoxNzg3MzMzNzcxfQ.bGdTzF5v29VLoDP4h0Ivobya-KVLX_Q9Ecn-VPTW_AY
@walletId=9545bba1-f2bb-48a9-a65f-6921edd60137
@stockId=9fddcf01-5928-48af-a3a6-065980ed3ba4


# ### test_GET /auth/me
# GET {{Base_url}}/auth/me


### test_POST /auth/login
POST {{Base_url}}/auth/login


### Register POST/auth/register
POST {{Base_url}}/auth/register
Content-Type: application/json

{
    "email": "ammy9@mail.com",
    "password": "Ab123456",
    "confirmPassword": "Ab123456",
    "firstName": "ammy",
    "lastName": "codecamp",
    "mobile": "0812345600"
}


### Login POST/auth/login
POST {{Base_url}}/auth/login
Content-Type: application/json

{
    "email": "ammy9@mail.com",
    "password": "Ab123456"
}


### GetMe GET/auth/me
GET {{Base_url}}/auth/me
Authorization: Bearer {{token}}


########################################################
### wallet
### Created wallet POST/wallet/walletCrete
POST {{Base_url}}/wallet/walletCreate
Authorization: Bearer {{token}}


### deposit wallet POST/wallet/deposit
POST {{Base_url}}/wallet/deposit
Authorization: Bearer 
Content-Type: application/json

{
    "amount": 1000,
    "bookbankId":"1234567890",
    "bankName":"KBANK"
}


### withdraw wallet POST/wallet/withdraw
POST {{Base_url}}/wallet/withdraw
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "amount": 1000,
    "bookbankId":"1234567890",
    "bankName":"KBANK"
}


### GET wallet GET/wallet/myWallet
GET {{Base_url}}/wallet/myWallet
Authorization: Bearer {{token}}

####
GET {{Base_url}}/wallet/history
Authorization: Bearer {{token}}

#########################################################
### Stock
### post create stock POST/stock/stockcreate
POST {{Base_url}}/stock/stockcreate
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "symbol": "AAPL",
    "companyName":"Apple INC",
    "exchange":"NASDAQ NMS - GLOBAL MARKET",
    "currency":"USD",
    "logo":"https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AAPL.png",
    "inductry":"Technology"
}


### Get stocks GEt/stock/stocks
Get {{Base_url}}/stock/stocks
Authorization: Bearer {{token}}


### Get stocksBySymbol GET/stock/stocks/:symbol
GET {{Base_url}}/stock/stocks/GOOGL
Authorization: Bearer {{token}}


### GET search stock    GET/stock/stocks?search=Alphabet
GET {{Base_url}}/stock/stocks?search=Alphabet
Authorization: Bearer {{token}}


### PATCH Stock        PATCH/stock/stocks/:id
PATCH {{Base_url}}/stock/stocks/{{stockId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "companyName":"Alphabet Inc",
    "exchange":"NASDAQ",
    "currency":"USD",
    "logo":"",
    "industry":""
}


### PATCH updateStockStatus      PATCH/stock/stocks/:id/status
PATCH {{Base_url}}/stock/stocks/{{stockId}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "isActive":true
}

### GET stock from finnhub     GET/stock/stocks/test
GET {{Base_url}}/stock/stocks/import
Authorization: Bearer {{token}}


#########################################################

### market
### Get market from finnhub     GET/market/quote
GET {{Base_url}}/market/quote/AAPL
Authorization: Bearer {{token}}




### GET testcandle from alpha_vantage      GET/candle/importhistorical/AAPL
GET {{Base_url}}/candle/importhistorical/AAPL
Authorization: Bearer {{token}}


###GET candle from  database   GET candle/getcandle/AAPL
GET {{Base_url}}/candle/getcandle/AAPL
Authorization: Bearer {{token}}


#########################################################

### Trade 

### POST trade buy stock     POST/trade/buy
POST {{Base_url}}/trade/buy
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "symbol":"AAPL",
    "quantity":100
}

### POST trade sell stock     POST/trade/sell
POST {{Base_url}}/trade/sell
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "symbol":"AAPL",
    "quantity":100
}

### GET  trade portfolio        GET/trade/portfolio
GET {{Base_url}}/trade/portfolio
Authorization: Bearer {{token}}

### GET portfolio stock
GET {{Base_url}}/trade/portfolio/port
Authorization: Bearer {{token}}


#########################################################

GET {{Base_url}}/transaction/port
Authorization: Bearer {{token}}
