@Base_url=http://localhost:8801/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzOWQ1YmJiLTE5NmMtNGY4OC04YWE2LTVkZjRiMzcwYmRmNyIsImlhdCI6MTc4Nzg1MzU2NCwiZXhwIjoxNzg3OTM5OTY0fQ.f6_77PKlNxyDFrw_zetjb-XiFbkUY0Vw1NjYO0uOq20
@walletId=b3197c06-f5bf-43d8-981c-8e2ce15fe9ce
@stockId=2754082c-0417-4a9f-b136-cce0cd1fc0b4


# ### test_GET /auth/me
# GET {{Base_url}}/auth/me


### test_POST /auth/login
POST {{Base_url}}/auth/login


### Register POST/auth/register
POST {{Base_url}}/auth/register
Content-Type: application/json

{
    "email": "ammy3@mail.com",
    "password": "Ab123456",
    "confirmPassword": "Ab123456",
    "firstName": "ammy",
    "lastName": "codecamp",
    "mobile": "0812345613"
}


### Login POST/auth/login
POST {{Base_url}}/auth/login
Content-Type: application/json

{
    "email": "ammy@mail.com",
    "password": "Ab123456"
}


### GetMe GET/auth/me
GET {{Base_url}}/auth/me
Authorization: Bearer {{token}}


########################################################
### wallet
### Created wallet POST/wallet/walletCrete
POST {{Base_url}}/wallet/walletCreate
Authorization: Bearer {{token}}


### deposit wallet POST/wallet/deposit
POST {{Base_url}}/wallet/deposit
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "amount": 10000,
    "bookbankId":"1234567890",
    "bankName":"KBANK"
}


### withdraw wallet POST/wallet/withdraw
POST {{Base_url}}/wallet/withdraw
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "amount": 70000,
    "bookbankId":"1234567890",
    "bankName":"KBANK"
}


### GET wallet GET/wallet/myWallet
GET {{Base_url}}/wallet/myWallet
Authorization: Bearer {{token}}

####
GET {{Base_url}}/wallet/history
Authorization: Bearer {{token}}

#########################################################
### Stock
### post create stock POST/stock/stockcreate
POST {{Base_url}}/stock/stockcreate
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "symbol": "AAPL",
    "companyName":"Apple INC",
    "exchange":"NASDAQ NMS - GLOBAL MARKET",
    "currency":"USD",
    "logo":"https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AAPL.png",
    "inductry":"Technology"
}


### Get stocks GEt/stock/stocks
Get {{Base_url}}/stock/stocks
Authorization: Bearer {{token}}


### Get stocksBySymbol GET/stock/stocks/:symbol
GET {{Base_url}}/stock/stocks/AMD
Authorization: Bearer {{token}}


### GET search stock    GET/stock/stocks?search=Alphabet
GET {{Base_url}}/stock/stocks?search=Alphabet
Authorization: Bearer {{token}}


### PATCH Stock        PATCH/stock/stocks/:id
PATCH {{Base_url}}/stock/stocks/{{stockId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "companyName":"Advanced Micro Devices Inc_ing",
    "exchange":"NASDAQ NMS - GLOBAL MARKET",
    "currency":"USD",
    "industry":"Semiconductors"
}


### PATCH updateStockStatus      PATCH/stock/stocks/:id/status
PATCH {{Base_url}}/stock/stocks/{{stockId}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "isActive":true
}

### GET stock from finnhub     GET/stock/stocks/test
GET {{Base_url}}/stock/stocks/import
Authorization: Bearer {{token}}


### POST creat favorites stock      POST/stock/favorite
POST {{Base_url}}/stock/{{stockId}}/favorite
Authorization: Bearer {{token}}


###Delete delete favorite stock
DELETE {{Base_url}}/stock/{{stockId}}/favorite
Authorization: Bearer {{token}}


###GET  Get favorite stock
GET {{Base_url}}/stock/{{stockId}}/favorite
Authorization: Bearer {{token}}


###GET favorite stock all

GET {{Base_url}}/stock/favorite
Authorization: Bearer {{token}}

#########################################################

### market
### Get market from finnhub     GET/market/quote/:symbol
GET {{Base_url}}/market/quote/AAPL
Authorization: Bearer {{token}}




### GET testcandle from alpha_vantage      GET/candle/importhistorical/AAPL
GET {{Base_url}}/candle/importhistorical/AAPL
Authorization: Bearer {{token}}


###GET candle from  database   GET/candle/getcandle/AAPL
GET {{Base_url}}/candle/getcandle/AAPL
Authorization: Bearer {{token}}


#########################################################

### Trade 

### POST trade buy stock     POST/trade/buy
POST {{Base_url}}/trade/buy
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "symbol":"AAPL",
    "quantity":100
}

### POST trade sell stock     POST/trade/sell
POST {{Base_url}}/trade/sell
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "symbol":"AAPL",
    "quantity":100
}

### GET  trade portfolio        GET/trade/portfolio
GET {{Base_url}}/trade/portfolio
Authorization: Bearer {{token}}

### GET portfolio stock
GET {{Base_url}}/trade/portfolio/port
Authorization: Bearer {{token}}


#########################################################

GET {{Base_url}}/transaction/port
Authorization: Bearer {{token}}
