@Base_url=http://localhost:8801/api

###
GET {{Base_url}}/auth/me

###
GET {{Base_url}}/auth/me

###
POST {{Base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "identity" : "andy@mail.com",
    "password" : "123456"
}

### 
POST {{Base_url}}/post HTTP/1.1
Content-Type: application/json

{
    "message": "sample"
}